version: "3.3"

services:
  nginx:
    container_name: nginx
    image: "nginx:alpine-slim"
    ports:
      - "7000:7000"
    networks:
      - transcendence
    restart: on-failure
    volumes:
      - "./nginx:/etc/nginx/conf.d"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    networks:
      - transcendence
    env_file: ./frontend/.env.production
    restart: on-failure

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    networks:
      - transcendence
    env_file: ./backend/.env.docker
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    container_name: postgres
    image: "postgres:alpine"
    networks:
      - transcendence
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    restart: on-failure

networks:
  transcendence:
    name: "transcendence"
    driver: bridge

volumes:
  postgres_vol:
    name: "postgres_vol"
