# Test get all users
GET http://localhost:3000/user/

# Test create random user
POST http://localhost:3000/user/random

# Test get a single user by id
GET http://localhost:3000/user/1

# Test create a user
POST http://localhost:3000/user
Content-Type: application/json

{
    "avatar": "https://s1.static.brasilescola.uol.com.br/be/conteudo/images/sigmund-freud.jpg",
    "email": "sigmundfreud@gmail.com",
    "firstName": "Sigmund",
    "lastName": "Freud",
    "status": "on",
    "fullName": "Sigmund Freud",
    "intraLogin": "sig-fre"
}

# Test delete a user by id
DELETE http://localhost:3000/user/1

########################################
